# Nos capítulos anteriores...

No primeiro arquivo fizemos uma análise exploratória dos dados dos experimentos e no segundo arquivo, analizamos os dados dos resultados dos experimentos. Está na hora e juntarmos esses dois conjutos de dados e utilizarmos técnicas de machine learning para tentar fazer preivisões de problemas. 
Mas antes, precisamos carregar novamente os bancos de dados.

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore') #ignora as mensagens de aviso

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
url_dados = 'https://github.com/alura-cursos/imersaodados3/blob/main/dados/dados_experimentos.zip?raw=true'
df = pd.read_csv(url_dados, compression = 'zip')
df.head()

id tratamento  tempo dose  ...    c-96    c-97    c-98    c-99
0  id_000644bb2  com_droga     24   D1  ... -0.3981  0.2139  0.3801  0.4176
1  id_000779bfc  com_droga     72   D1  ...  0.1522  0.1241  0.6077  0.7371
2  id_000a6266a  com_droga     48   D1  ... -0.6417 -0.2187 -1.4080  0.6931
3  id_0015fd391  com_droga     48   D1  ... -1.6210 -0.8784 -0.3876 -0.8154
4  id_001626bd3  com_droga     72   D2  ...  0.1094  0.2885 -0.3786  0.7125

[5 rows x 877 columns]

In [4]:
#Renomeando as colunas, eliminando '-'
colunas = df.columns.to_numpy()  #cria um array com os nomes das colunas
for i in range(0,colunas.shape[0]):
   colunas[i] = colunas[i].replace('-','')  #faz um loop percorrendo os índices do array, trocando '-' por ''
df.columns = colunas  #renomeia as colunas
df.rename(columns= {'droga':'composto'}, inplace = True) #renomeia a coluna 'droga' para 'composto'
df.tail() #mostra os 5 últimos regristos

id    tratamento  tempo dose  ...     c96     c97     c98     c99
23809  id_fffb1ceed     com_droga     24   D2  ...  0.0631  0.9171  0.5258  0.4680
23810  id_fffb70c0c     com_droga     24   D2  ... -0.2084 -0.1224 -0.2715  0.3689
23811  id_fffc1c3f4  com_controle     48   D2  ...  0.2256  0.7592  0.6656  0.3808
23812  id_fffcb9e7c     com_droga     24   D1  ...  0.1732  0.7015 -0.6290  0.0740
23813  id_ffffdd77b     com_droga     72   D1  ... -3.5770 -0.4775 -2.1500 -4.2520

[5 rows x 877 columns]

In [5]:
df_resultados = pd.read_csv('https://github.com/alura-cursos/imersaodados3/blob/main/dados/dados_resultados.csv?raw=true')
df_resultados

id  ...  wnt_inhibitor
0      id_000644bb2  ...              0
1      id_000779bfc  ...              0
2      id_000a6266a  ...              0
3      id_0015fd391  ...              0
4      id_001626bd3  ...              0
...             ...  ...            ...
23809  id_fffb1ceed  ...              0
23810  id_fffb70c0c  ...              0
23811  id_fffc1c3f4  ...              0
23812  id_fffcb9e7c  ...              0
23813  id_ffffdd77b  ...              0

[23814 rows x 207 columns]

In [6]:
df_resultados['n_moa'] = df_resultados.drop('id', axis=1).sum(axis=1)

In [7]:
df_resultados['ativo_moa'] = (df_resultados['n_moa'] != 0)*1
df_resultados.head()

id  5-alpha_reductase_inhibitor  ...  n_moa  ativo_moa
0  id_000644bb2                            0  ...      1          1
1  id_000779bfc                            0  ...      0          0
2  id_000a6266a                            0  ...      3          1
3  id_0015fd391                            0  ...      0          0
4  id_001626bd3                            0  ...      1          1

[5 rows x 209 columns]

In [8]:
df_total = pd.merge(df, df_resultados[['id','n_moa', 'ativo_moa']], on='id')
df_total.head()

id tratamento  tempo dose  ...     c98     c99  n_moa  ativo_moa
0  id_000644bb2  com_droga     24   D1  ...  0.3801  0.4176      1          1
1  id_000779bfc  com_droga     72   D1  ...  0.6077  0.7371      0          0
2  id_000a6266a  com_droga     48   D1  ... -1.4080  0.6931      3          1
3  id_0015fd391  com_droga     48   D1  ... -0.3876 -0.8154      0          0
4  id_001626bd3  com_droga     72   D2  ... -0.3786  0.7125      1          1

[5 rows x 879 columns]

In [9]:
df_total['Eh controle'] = (df_total['tratamento'] == 'com_controle')*1
df_total['Tempo eh 24'] = (df_total['tempo'] == 24)*1
df_total['Tempo eh 48'] = (df_total['tempo'] == 48)*1
df_total['Tempo eh 72'] = (df_total['tempo'] == 72)*1

# Máquinas preditivas

## Conceitos importantes

Antes iniciarmos a construção dos modelos, é necessário explicar alguns conceitos que surgirão em nossa análise.

A acurácia ('score', definida como total de acertos / total de amostras) não será a única métrica que utilizaremos para analisar a performace dos nossos modelos. Dependendo dos aspectos do problema de negócio, podemos estar interessandos em outras métricas.

Uma boa maneira de começar a melhorar a análise da performace do modelo é verificar sua matriz de confusão ('confusion matrix'). Nas linhas dessa matriz temos os resultados reais e nas colunas temos os resultados previstos pelo modelo, de acordo com cada classe. 


Em problemas de classificação binária, será uma matrix 2x2. 

Nas células dessa matriz, temos 4 informações importantes:
- VP = número de verdadeiros positivos (modelo previu que era positivo e de fato era positivo)
- VN = número de verdadeiros negativos (modelo previu que era negativo e de fato era negativo)
- FP = número de falsos positivos (modelo previu que era positivo, mas na verdade era negativo)
- FN = número de falsos negativos (modelo previu que era negativo, mas na verdade era positivo)

Dependendo do nosso problema, talvez queiramos um modelo com baixa proporção de falsos negativos, ou talvez uma baixa proporção de falsos positivos. 

Temos métricas que medem isso:
- precisão de positos = VP/(VP+FP)
- precisão de negativos = VN/(VN+FN)
- recall (ou revocação) de positivos = VP/(VP+FN)
- recall (ou revocação) de negativos = VN/(VN+FP)
- F1 = média harmônica entre presicão e revocação

## Problema 1: Prevendo se o composto ativa algum MOA

Como primeiro exemplo, vamos constuir máquinas que prevem se um composto ativa pelo menos um MOA (sem especificar qual é o MOA). Compostos que não ativam nenhum MOA provavelmente não são interessantes. 
Nesse caso, não queremos correr o risco de prever que um composto ativa, porém na verdade não ativa. Ou seja, falsos positivos não são bem-vindos nesse problema. Logo estamos interessando em modelos com alta precisão para positivos. 

Para começar, devemos separar, dentre as colunas do nosso data frame, aquelas que servirão para alimentar as máquinas preditivas e aquela que será a informação a ser prevista. 
Nesse primeiro momento, como variável a ser prevista, utilizaremos y = ativo_moa, isto é, vamos prever se o composto irá ou não ativar algum moa. 
Como parâmetros na variável x, iremos passar dados de dose, tempo, as expressões gênicas e as viabilidades celuares. 

Importante lembrar que já observamos que as viabilidades celuares são variáveis com alta correção entre si. Talvez seja então interessante não considerar todas elas no modelo preditivo. Como já vimos na Aula 5 que as máquinas construídas lá não obtivaram um score muito bom e foram utilizadas todas as viabilidades celuares, nos meus modelos decidi utilizar apenas c0 e ver se os resultados são melhores. 

In [ ]:
y = df_total['ativo_moa']
x_aux = df_total.drop(['id', 'tratamento', 'tempo','dose', 'composto', 'ativo_moa'], axis = 1)
x = x_aux.drop(x_aux.columns[773:873], axis = 1)

Agora iremos separar nossos conjuntos de treino e conjunto de teste.

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3, stratify = y)

Estamos prontos para começar a testar os modelos preditivos.
Vamos criar também um dataframe com informações sumarizadas das performaces de cada modelo, para que possamos compará-los no final. Criaremos listas que coletarão os resultados das métricas de análise e no fim do processo utilizaremos essas listas como colunas do nosso dataframe. Assim:

In [ ]:
lista_modelo = []
lista_score = []
lista_precision0 = [] 
lista_precision1 = []
lista_recall0 = []
lista_recall1 = []

### Regressão Logistica

In [ ]:
modelo = LogisticRegression()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  66.01819454163751 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)


[[1043 1767]
 [ 661 3674]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.61      0.37      0.46      2810
           1       0.68      0.85      0.75      4335

    accuracy                           0.66      7145
   macro avg       0.64      0.61      0.61      7145
weighted avg       0.65      0.66      0.64      7145



### DecisionTreeClassifier 

In [ ]:
modelo = DecisionTreeClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  62.02939118264521 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[1441 1369]
 [1344 2991]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.52      0.51      0.52      2810
           1       0.69      0.69      0.69      4335

    accuracy                           0.62      7145
   macro avg       0.60      0.60      0.60      7145
weighted avg       0.62      0.62      0.62      7145



### RandomFlorestClassifier

In [ ]:
modelo = RandomForestClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  67.30580825752274 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[ 783 2027]
 [ 309 4026]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.72      0.28      0.40      2810
           1       0.67      0.93      0.78      4335

    accuracy                           0.67      7145
   macro avg       0.69      0.60      0.59      7145
weighted avg       0.69      0.67      0.63      7145



### LGBMClassifier

In [ ]:
modelo = LGBMClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  68.24352694191742 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[ 808 2002]
 [ 267 4068]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.75      0.29      0.42      2810
           1       0.67      0.94      0.78      4335

    accuracy                           0.68      7145
   macro avg       0.71      0.61      0.60      7145
weighted avg       0.70      0.68      0.64      7145



### XGBClassifier

In [ ]:
modelo = XGBClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  68.99930020993702 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[ 630 2180]
 [  35 4300]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      0.22      0.36      2810
           1       0.66      0.99      0.80      4335

    accuracy                           0.69      7145
   macro avg       0.81      0.61      0.58      7145
weighted avg       0.78      0.69      0.63      7145



### GradientBoostingClassifier


In [ ]:
modelo = GradientBoostingClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  69.06927921623513 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[ 642 2168]
 [  42 4293]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.94      0.23      0.37      2810
           1       0.66      0.99      0.80      4335

    accuracy                           0.69      7145
   macro avg       0.80      0.61      0.58      7145
weighted avg       0.77      0.69      0.63      7145



### KNeighborsClassifier

In [ ]:
modelo = KNeighborsClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  61.371588523442966 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[1020 1790]
 [ 970 3365]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.51      0.36      0.42      2810
           1       0.65      0.78      0.71      4335

    accuracy                           0.61      7145
   macro avg       0.58      0.57      0.57      7145
weighted avg       0.60      0.61      0.60      7145



### Support Vector Machine

In [ ]:
modelo = SVC()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  68.45346396081176 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[ 702 2108]
 [ 146 4189]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.83      0.25      0.38      2810
           1       0.67      0.97      0.79      4335

    accuracy                           0.68      7145
   macro avg       0.75      0.61      0.59      7145
weighted avg       0.73      0.68      0.63      7145



### Resumo 

Vamos sumarizar essas informações sobre a performace das máquinas preditivas em uma tabela. 

In [ ]:
Tabela_Performace_Modelos = pd.DataFrame()
Tabela_Performace_Modelos['Modelo'] = lista_modelo
Tabela_Performace_Modelos['Score'] = lista_score
Tabela_Performace_Modelos['precision-0'] = lista_precision0
Tabela_Performace_Modelos['precision-1'] = lista_precision1
Tabela_Performace_Modelos['recall-0'] = lista_recall0
Tabela_Performace_Modelos['recall-1'] = lista_recall1

Tabela_Comparação_Modelos_Problema1 = Tabela_Performace_Modelos
Tabela_Comparação_Modelos_Problema1

Modelo     Score  ...  recall-0  recall-1
0          LogisticRegression  0.660182  ...  0.371174  0.847520
1      DecisionTreeClassifier  0.620294  ...  0.512811  0.689965
2      RandomForestClassifier  0.673058  ...  0.278648  0.928720
3              LGBMClassifier  0.682435  ...  0.287544  0.938408
4               XGBClassifier  0.689993  ...  0.224199  0.991926
5  GradientBoostingClassifier  0.690693  ...  0.228470  0.990311
6        KNeighborsClassifier  0.613716  ...  0.362989  0.776240
7                         SVC  0.684535  ...  0.249822  0.966321

[8 rows x 6 columns]

Percebemos então que a acurácia dos modelos não é boa. Mas como já explicado, estamos também muito interessados na precisão dos resultados positivos, o que também não são bons, nunca chegando a 70%. 
Levando em conta a acurácia e a precisão, concluímos que nenhum dos modelos é satisfatório para resolver o Problema 1. O que faz sentindo, pois perguntar se ativa algum moa parece algo bastante vago. 
Está claro então que precisamos melhorar a pergunta que queremos responder utilizando a máquina preditiva. Vamos mudar a abordagem.

## Problema 2: Prevendo se o composto ativa 2 ou mais MOAs

No Problema 1 estávamos interessando em saber se um composto ativa pelo menos 1 MOA. O Problema 2 é similar: queremos saber se um composto, com base em suas expressões gênicas, ativa 2 ou mais MOA. Ainda é uma pergunta vaga, mas veremos que os resultados são mais animadores. 

Vamos começar definindo a nossa variável alvo:

In [ ]:
df_total['ativa_2moa'] = (df_total['n_moa'] > 1)*1

Vejamos como é a distrubuição de valores dessa variável:

In [ ]:
df_total['ativa_2moa'].value_counts()

0    21899
1     1915
Name: ativa_2moa, dtype: int64

Observamos então que os dados estão bem desbalanceados. Isso pode afetar o desepenho dos modelos preditivos. Nesse tipo de cenário, é razoável esperar uma acurácia muito alta. Por esse motivo, mais do que nunca, é crucial considerar também a precisão de positivos. 

In [ ]:
y = df_total['ativa_2moa']
x_aux = df_total.drop(['id', 'tratamento', 'tempo','dose', 'composto', 'ativo_moa', 'ativa_2moa'], axis = 1)
x = x_aux.drop(x_aux.columns[773:873], axis = 1)

Agora iremos separar nossos conjuntos de treino e conjunto de teste.

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3, stratify = y)

Como antes, vamos criar também um dataframe com informações sumarizadas das performaces de cada modelo:

In [ ]:
lista_modelo = []
lista_score = []
lista_precision0 = [] 
lista_precision1 = []
lista_recall0 = []
lista_recall1 = []

### Regressão Logistica

In [ ]:
modelo = LogisticRegression()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  94.61161651504548 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6527   43]
 [ 342  233]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97      6570
           1       0.84      0.41      0.55       575

    accuracy                           0.95      7145
   macro avg       0.90      0.70      0.76      7145
weighted avg       0.94      0.95      0.94      7145



### DecisionTreeClassifier 

In [ ]:
modelo = DecisionTreeClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  89.58712386284114 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6158  412]
 [ 332  243]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      0.94      0.94      6570
           1       0.37      0.42      0.40       575

    accuracy                           0.90      7145
   macro avg       0.66      0.68      0.67      7145
weighted avg       0.90      0.90      0.90      7145



### RandomFlorestClassifier

In [ ]:
modelo = RandomForestClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  94.9335199440168 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6562    8]
 [ 354  221]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      6570
           1       0.97      0.38      0.55       575

    accuracy                           0.95      7145
   macro avg       0.96      0.69      0.76      7145
weighted avg       0.95      0.95      0.94      7145



### LGBMClassifier

In [ ]:
modelo = LGBMClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  95.01749475157453 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6563    7]
 [ 349  226]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      6570
           1       0.97      0.39      0.56       575

    accuracy                           0.95      7145
   macro avg       0.96      0.70      0.77      7145
weighted avg       0.95      0.95      0.94      7145



### XGBClassifier

In [ ]:
modelo = XGBClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  94.96151154653603 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6563    7]
 [ 353  222]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      6570
           1       0.97      0.39      0.55       575

    accuracy                           0.95      7145
   macro avg       0.96      0.69      0.76      7145
weighted avg       0.95      0.95      0.94      7145



### GradientBoostingClassifier


In [ ]:
modelo = GradientBoostingClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  94.77956613016096 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6551   19]
 [ 354  221]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      6570
           1       0.92      0.38      0.54       575

    accuracy                           0.95      7145
   macro avg       0.93      0.69      0.76      7145
weighted avg       0.95      0.95      0.94      7145



### KNeighborsClassifier

In [ ]:
modelo = KNeighborsClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  94.6815955213436 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6542   28]
 [ 352  223]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      6570
           1       0.89      0.39      0.54       575

    accuracy                           0.95      7145
   macro avg       0.92      0.69      0.76      7145
weighted avg       0.94      0.95      0.94      7145



### Support Vector Machine

In [ ]:
modelo = SVC()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  94.63960811756473 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6563    7]
 [ 376  199]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      6570
           1       0.97      0.35      0.51       575

    accuracy                           0.95      7145
   macro avg       0.96      0.67      0.74      7145
weighted avg       0.95      0.95      0.93      7145



### Resumo

In [ ]:
Tabela_Performace_Modelos = pd.DataFrame()
Tabela_Performace_Modelos['Modelo'] = lista_modelo
Tabela_Performace_Modelos['Score'] = lista_score
Tabela_Performace_Modelos['precision-0'] = lista_precision0
Tabela_Performace_Modelos['precision-1'] = lista_precision1
Tabela_Performace_Modelos['recall-0'] = lista_recall0
Tabela_Performace_Modelos['recall-1'] = lista_recall1

Tabela_Comparação_Modelos_Problema2 = Tabela_Performace_Modelos
Tabela_Comparação_Modelos_Problema2

Modelo     Score  ...  recall-0  recall-1
0          LogisticRegression  0.946116  ...  0.993455  0.405217
1      DecisionTreeClassifier  0.895871  ...  0.937291  0.422609
2      RandomForestClassifier  0.949335  ...  0.998782  0.384348
3              LGBMClassifier  0.950175  ...  0.998935  0.393043
4               XGBClassifier  0.949615  ...  0.998935  0.386087
5  GradientBoostingClassifier  0.947796  ...  0.997108  0.384348
6        KNeighborsClassifier  0.946816  ...  0.995738  0.387826
7                         SVC  0.946396  ...  0.998935  0.346087

[8 rows x 6 columns]

Vemos que para o Problema 2, a acurácia de todos os modelos foi bastante alta, acima de 94%, como era de se esperar. Por isso, damos atenção à métrica precisão e notamos que também estão razoáveis. 
Com excessão do modelo de árvore de decisão, todos os outros modelos tiveram uma precisão acima de 84%. Alguns obtiveram precisão acima de 96%, o que é impressionante. 

Porém, uma métrica tão boa assim não vem de graça. É razoável esperar que outra métricas sejam afetadas negativamente. Vemos que em todos os modelos, o recall de positivos é baixo, sempre menor que 45%. 
Ou seja, existe um número proporcionalmente grande de falsos negativos. No nosso problema de negócios, isso significa que haverá um número grande de compostos cujo modelo prevê que não ativará os MOAs, mas na verdade ele ativará. Estamos perdendo oportunidades. 

Mas vale frisar novamente que uma alta precisão para positivos significa que temos uma proporção baixa de falsos positivos. Ou seja, estamos correndo um risco menor de aprovar um composto que não funcione (ou funcione de uma maneira que não é a desejada). 
Fica a cargo do tomador de decisão escolher qual cenário é preferível. 

## Problema 3: Prevendo se o composto ativa um MOA específico

No Problema 1 estávamos interessando em saber se um composto ativa pelo menos 1 MOA. No Problema 3 estamos interessados em saber se o composto ativa um MOA de nossa escolha. Biologicamente, esse problema faz bastante sentido e é parece ser mais relevante. 



Podemos ver esse problema sob duas perspectivas:
 

1.   queremos garantir que o composto ative o MOA, pois é benéfico para o paciente
2.   queremos garantir que o composto não ative o MOA, pois seria maléfico para o paciente



No primeiro cenário, queremos uma baixa proporção de falsos positivos, ou seja, uma precisão alta para positivos. No segundo cenário, queremos uma proporção baixa para falsos negativos, ou seja, uma precisão alta para negativos.

Para efeito de exemplificação, vamos escolher o MOA proteasome_inhibitor. Esse é o MOA que mais foi ativado, com 762 ativações. 

Para realizarmos isso, vamos precisar criar um novo data frame, utilizando o merge. 

In [ ]:
df_moa_ativado = pd.merge(df.iloc[:,0:778], df_resultados[['id','proteasome_inhibitor']], on='id')
df_moa_ativado

In [ ]:
df_moa_ativado['Eh controle'] = (df_moa_ativado['tratamento'] == 'com_controle')*1
df_moa_ativado['Tempo eh 24'] = (df_moa_ativado['tempo'] == 24)*1
df_moa_ativado['Tempo eh 48'] = (df_moa_ativado['tempo'] == 48)*1
df_moa_ativado['Tempo eh 72'] = (df_moa_ativado['tempo'] == 72)*1

Criando as variáveis:

In [ ]:
y = df_moa_ativado['proteasome_inhibitor']
x = df_moa_ativado.drop(['id', 'tratamento','composto' ,'dose', 'tempo', 'proteasome_inhibitor'], axis = 1)

Agora iremos separar nossos conjuntos de treino e conjunto de teste.

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3, stratify = y)

Estamos prontos para começar a testar os modelos preditivos.
Como antes, vamos criar também um dataframe com informações sumarizadas das performaces de cada modelo. Assim:

In [ ]:
lista_modelo = []
lista_score = []
lista_precision0 = [] 
lista_precision1 = []
lista_recall0 = []
lista_recall1 = []

### Regressão Logistica

In [ ]:
modelo = LogisticRegression()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.95801259622114 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6925    2]
 [   1  217]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6927
           1       0.99      1.00      0.99       218

    accuracy                           1.00      7145
   macro avg       1.00      1.00      1.00      7145
weighted avg       1.00      1.00      1.00      7145



### DecisionTreeClassifier 

In [ ]:
modelo = DecisionTreeClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.72008397480757 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6918    9]
 [  11  207]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6927
           1       0.96      0.95      0.95       218

    accuracy                           1.00      7145
   macro avg       0.98      0.97      0.98      7145
weighted avg       1.00      1.00      1.00      7145



### RandomFlorestClassifier

In [ ]:
modelo = RandomForestClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.94401679496151 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6924    3]
 [   1  217]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6927
           1       0.99      1.00      0.99       218

    accuracy                           1.00      7145
   macro avg       0.99      1.00      1.00      7145
weighted avg       1.00      1.00      1.00      7145



### LGBMClassifier

In [ ]:
modelo = LGBMClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.91602519244228 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6924    3]
 [   3  215]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6927
           1       0.99      0.99      0.99       218

    accuracy                           1.00      7145
   macro avg       0.99      0.99      0.99      7145
weighted avg       1.00      1.00      1.00      7145



### XGBClassifier

In [ ]:
modelo = XGBClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.91602519244228 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6924    3]
 [   3  215]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6927
           1       0.99      0.99      0.99       218

    accuracy                           1.00      7145
   macro avg       0.99      0.99      0.99      7145
weighted avg       1.00      1.00      1.00      7145



### GradientBoostingClassifier


In [ ]:
modelo = GradientBoostingClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.88803358992303 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6923    4]
 [   4  214]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6927
           1       0.98      0.98      0.98       218

    accuracy                           1.00      7145
   macro avg       0.99      0.99      0.99      7145
weighted avg       1.00      1.00      1.00      7145



### KNeighborsClassifier

In [ ]:
modelo = KNeighborsClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.76207137858643 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6911   16]
 [   1  217]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6927
           1       0.93      1.00      0.96       218

    accuracy                           1.00      7145
   macro avg       0.97      1.00      0.98      7145
weighted avg       1.00      1.00      1.00      7145



### Support Vector Machine

In [ ]:
modelo = SVC()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.65010496850944 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6922    5]
 [  20  198]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6927
           1       0.98      0.91      0.94       218

    accuracy                           1.00      7145
   macro avg       0.99      0.95      0.97      7145
weighted avg       1.00      1.00      1.00      7145



### Resumo

In [ ]:
Tabela_Performace_Modelos = pd.DataFrame()
Tabela_Performace_Modelos['Modelo'] = lista_modelo
Tabela_Performace_Modelos['Score'] = lista_score
Tabela_Performace_Modelos['precision-0'] = lista_precision0
Tabela_Performace_Modelos['precision-1'] = lista_precision1
Tabela_Performace_Modelos['recall-0'] = lista_recall0
Tabela_Performace_Modelos['recall-1'] = lista_recall1

Tabela_Comparação_Modelos_Problema3 = Tabela_Performace_Modelos
Tabela_Comparação_Modelos_Problema3

Modelo     Score  ...  recall-0  recall-1
0          LogisticRegression  0.999580  ...  0.999711  0.995413
1      DecisionTreeClassifier  0.997201  ...  0.998701  0.949541
2      RandomForestClassifier  0.999440  ...  0.999567  0.995413
3              LGBMClassifier  0.999160  ...  0.999567  0.986239
4               XGBClassifier  0.999160  ...  0.999567  0.986239
5  GradientBoostingClassifier  0.998880  ...  0.999423  0.981651
6        KNeighborsClassifier  0.997621  ...  0.997690  0.995413
7                         SVC  0.996501  ...  0.999278  0.908257

[8 rows x 6 columns]

Olhando os dados da tabela 3, concluímos que, para o Problema 3, todos os modelos tiveram excelente desemepenho, em todas as métricas. Não poderíamos pedir por algo melhor. 

## Problema 4: Prevendo se o composto é do grupo de controle

Agora estamos interessado em outro tipo de situação. Imagine que por um erro alguns dos rótulos dos compostos foram perdidos. Agora não se sabe se o composto era do grupo de controle ou não. Gostaríamos de poder prever essa informação. 
Para esse problema, imagino que estamos interessados tanto em baixa proporção de falsos positivos quanto em baixa proporção de falsos negativos. 

Para realizarmos isso, vamos voltar ao nosso data frame df_total. Nossa variável alvo será 'Eh controle' e a máquina preditiva irá receber as expressões gênicas, a viabilidade celular, o tempo do experimento e as doses.

In [ ]:
df_total

id    tratamento  tempo  ... Tempo eh 48 Tempo eh 72  ativa_2moa
0      id_000644bb2     com_droga     24  ...           0           0           0
1      id_000779bfc     com_droga     72  ...           0           1           0
2      id_000a6266a     com_droga     48  ...           1           0           1
3      id_0015fd391     com_droga     48  ...           1           0           0
4      id_001626bd3     com_droga     72  ...           0           1           0
...             ...           ...    ...  ...         ...         ...         ...
23809  id_fffb1ceed     com_droga     24  ...           0           0           0
23810  id_fffb70c0c     com_droga     24  ...           0           0           0
23811  id_fffc1c3f4  com_controle     48  ...           1           0           0
23812  id_fffcb9e7c     com_droga     24  ...           0           0           0
23813  id_ffffdd77b     com_droga     72  ...           0           1           0

[23814 rows x 884 columns]

Criando as variáveis:

In [ ]:
y = df_total['Eh controle']
x_aux = df_total.drop(['id', 'tratamento', 'tempo','dose', 'composto', 'ativo_moa', 'ativa_2moa', 'Eh controle'], axis = 1)
x = x_aux.drop(x_aux.columns[773:873], axis = 1)

Agora iremos separar nossos conjuntos de treino e conjunto de teste.

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3, stratify = y)

Como antes, vamos criar também um dataframe com informações sumarizadas das performaces de cada modelo.

In [ ]:
lista_modelo = []
lista_score = []
lista_precision0 = [] 
lista_precision1 = []
lista_recall0 = []
lista_recall1 = []

### Regressão Logistica

In [ ]:
modelo = LogisticRegression()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  95.0594821553534 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6417  168]
 [ 185  375]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      6585
           1       0.69      0.67      0.68       560

    accuracy                           0.95      7145
   macro avg       0.83      0.82      0.83      7145
weighted avg       0.95      0.95      0.95      7145



### DecisionTreeClassifier 

In [ ]:
modelo = DecisionTreeClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  88.91532540237928 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6169  416]
 [ 376  184]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94      6585
           1       0.31      0.33      0.32       560

    accuracy                           0.89      7145
   macro avg       0.62      0.63      0.63      7145
weighted avg       0.89      0.89      0.89      7145



### RandomFlorestClassifier

In [ ]:
modelo = RandomForestClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  92.9741077676697 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6577    8]
 [ 494   66]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.93      1.00      0.96      6585
           1       0.89      0.12      0.21       560

    accuracy                           0.93      7145
   macro avg       0.91      0.56      0.59      7145
weighted avg       0.93      0.93      0.90      7145



### LGBMClassifier

In [ ]:
modelo = LGBMClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  95.0594821553534 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6518   67]
 [ 286  274]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97      6585
           1       0.80      0.49      0.61       560

    accuracy                           0.95      7145
   macro avg       0.88      0.74      0.79      7145
weighted avg       0.95      0.95      0.94      7145



### XGBClassifier

In [ ]:
modelo = XGBClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  94.61161651504548 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6517   68]
 [ 317  243]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97      6585
           1       0.78      0.43      0.56       560

    accuracy                           0.95      7145
   macro avg       0.87      0.71      0.76      7145
weighted avg       0.94      0.95      0.94      7145



### GradientBoostingClassifier


In [ ]:
modelo = GradientBoostingClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  94.44366689993002 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6500   85]
 [ 312  248]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97      6585
           1       0.74      0.44      0.56       560

    accuracy                           0.94      7145
   macro avg       0.85      0.71      0.76      7145
weighted avg       0.94      0.94      0.94      7145



### KNeighborsClassifier

In [ ]:
modelo = KNeighborsClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  93.65990202939119 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6519   66]
 [ 387  173]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.94      0.99      0.97      6585
           1       0.72      0.31      0.43       560

    accuracy                           0.94      7145
   macro avg       0.83      0.65      0.70      7145
weighted avg       0.93      0.94      0.92      7145



### Support Vector Machine

In [ ]:
modelo = SVC()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  95.52134359692093 %


In [ ]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6516   69]
 [ 251  309]]


In [ ]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98      6585
           1       0.82      0.55      0.66       560

    accuracy                           0.96      7145
   macro avg       0.89      0.77      0.82      7145
weighted avg       0.95      0.96      0.95      7145



### Resumo

In [ ]:
Tabela_Performace_Modelos = pd.DataFrame()
Tabela_Performace_Modelos['Modelo'] = lista_modelo
Tabela_Performace_Modelos['Score'] = lista_score
Tabela_Performace_Modelos['precision-0'] = lista_precision0
Tabela_Performace_Modelos['precision-1'] = lista_precision1
Tabela_Performace_Modelos['recall-0'] = lista_recall0
Tabela_Performace_Modelos['recall-1'] = lista_recall1

Tabela_Comparação_Modelos_Problema4 = Tabela_Performace_Modelos
Tabela_Comparação_Modelos_Problema4

Modelo     Score  ...  recall-0  recall-1
0          LogisticRegression  0.950595  ...  0.974487  0.669643
1      DecisionTreeClassifier  0.889153  ...  0.936826  0.328571
2      RandomForestClassifier  0.929741  ...  0.998785  0.117857
3              LGBMClassifier  0.950595  ...  0.989825  0.489286
4               XGBClassifier  0.946116  ...  0.989674  0.433929
5  GradientBoostingClassifier  0.944437  ...  0.987092  0.442857
6        KNeighborsClassifier  0.936599  ...  0.989977  0.308929
7                         SVC  0.955213  ...  0.989522  0.551786

[8 rows x 6 columns]

Estudando a tabela com o resumo das análises, percebemos que as acurácias estão altas, porém as outras méticas estão dispersas. Em geral, os modelos tem uma alta precisão para negativos, o que é razoável de se pensar, pois temos muito mais amostras que não são do grupo de controle. A precisão para positovos está boa, em geral (com excessão do decision tree), porém a revocação para positivos está bem baixa. Isso significa que há muitos do grupo de controle que estão sendo classficados como não sendo do grupo de controle. 
Minha conclusão é que os modelos tem desempenho mediano. 

## Outros problemas

Gostaria de sugerir outros problemas que podem ser atacados utilizando as mesmas téncinas de machine learning. Não os resolvo aqui por questão de tempo. Porém, me comprometo a estudar esses problemas nos próximos dias e então adicionar um outro arquivo no repositório, com as novas análises. 

### Prever se um composto ativa dois MOAs específicos.

Como a quantidade total de positivos será muito baixa (comparado com o total), espero uma acurácia alta, porém uma tendência à ter uma precisão baixa para positivos. 
Pretendo também testar como os modelos se saem com MOAs com alta correlação e MOAs com baixa correlação. 

### Prever se um composto ativa um MOA específico, mas não ativa outro MOA específico

Aqui espero um cenário similar ao do Problema 3, e portanto resultados similares. 

### Recuperar uma expressão gênica a partir dos MOAs ativados

Aqui estou propondo meio que o problema inverso do que estávamos fazendo. Não sei se faz sentido biológico ou não querer saber isso, mas achei interessante.
Obviamente, vou me concentrar em apenas uma expressão gênica (e.g., g0). 
Outro ponto a observar é que a natureza do problema é distinta. Até o momento, trabalhamos apenas com problemas de classficação binária. Este é um problema de regressão. Os modelos serão outros. 

### Recuperar o composto a partir das expressões gênicas

Agora trata-se um um problema de classficiação multi classe. Provavelmente será mais fácil se eu me restringir àqueles nove compostos mais frequentes. 

### Recuperar o composto a partir dos MOAs ativados

Similar ao problema anterior, com a vantagem de que penso ser mais fácil de se obter os dados em laboratório.
(quero dizer que penso que seja mais fácil verificar se um MOA foi ativado do que calcular a expressão gênica)