<a href="https://colab.research.google.com/github/renanmath/imersao-dados-desafio-final/blob/main/Alura_ImersaoDados_modelos_preditivos_(parte2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nos capítulos anteriores...

No primeiro arquivo fizemos uma análise exploratória dos dados dos experimentos e no segundo arquivo, analizamos os dados dos resultados dos experimentos. No terceiro arquivo criamos alguns modelos preditivos para resolver alguns problemas propostos. Nesse quarto arquivo, propomos e resolvemos novos problemas
Mas antes, precisamos carregar novamente os bancos de dados.

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore') #ignora as mensagens de aviso

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
url_dados = 'https://github.com/alura-cursos/imersaodados3/blob/main/dados/dados_experimentos.zip?raw=true'
df = pd.read_csv(url_dados, compression = 'zip')
df.head()

id tratamento  tempo dose  ...    c-96    c-97    c-98    c-99
0  id_000644bb2  com_droga     24   D1  ... -0.3981  0.2139  0.3801  0.4176
1  id_000779bfc  com_droga     72   D1  ...  0.1522  0.1241  0.6077  0.7371
2  id_000a6266a  com_droga     48   D1  ... -0.6417 -0.2187 -1.4080  0.6931
3  id_0015fd391  com_droga     48   D1  ... -1.6210 -0.8784 -0.3876 -0.8154
4  id_001626bd3  com_droga     72   D2  ...  0.1094  0.2885 -0.3786  0.7125

[5 rows x 877 columns]

In [4]:
#Renomeando as colunas, eliminando '-'
colunas = df.columns.to_numpy()  #cria um array com os nomes das colunas
for i in range(0,colunas.shape[0]):
   colunas[i] = colunas[i].replace('-','')  #faz um loop percorrendo os índices do array, trocando '-' por ''
df.columns = colunas  #renomeia as colunas
df.rename(columns= {'droga':'composto'}, inplace = True) #renomeia a coluna 'droga' para 'composto'
df.tail() #mostra os 5 últimos regristos

id    tratamento  tempo dose  ...     c96     c97     c98     c99
23809  id_fffb1ceed     com_droga     24   D2  ...  0.0631  0.9171  0.5258  0.4680
23810  id_fffb70c0c     com_droga     24   D2  ... -0.2084 -0.1224 -0.2715  0.3689
23811  id_fffc1c3f4  com_controle     48   D2  ...  0.2256  0.7592  0.6656  0.3808
23812  id_fffcb9e7c     com_droga     24   D1  ...  0.1732  0.7015 -0.6290  0.0740
23813  id_ffffdd77b     com_droga     72   D1  ... -3.5770 -0.4775 -2.1500 -4.2520

[5 rows x 877 columns]

In [5]:
df_resultados = pd.read_csv('https://github.com/alura-cursos/imersaodados3/blob/main/dados/dados_resultados.csv?raw=true')
df_resultados

id  ...  wnt_inhibitor
0      id_000644bb2  ...              0
1      id_000779bfc  ...              0
2      id_000a6266a  ...              0
3      id_0015fd391  ...              0
4      id_001626bd3  ...              0
...             ...  ...            ...
23809  id_fffb1ceed  ...              0
23810  id_fffb70c0c  ...              0
23811  id_fffc1c3f4  ...              0
23812  id_fffcb9e7c  ...              0
23813  id_ffffdd77b  ...              0

[23814 rows x 207 columns]

In [6]:
df_resultados['n_moa'] = df_resultados.drop('id', axis=1).sum(axis=1)

In [7]:
df_resultados['ativo_moa'] = (df_resultados['n_moa'] != 0)*1
df_resultados.head()

id  5-alpha_reductase_inhibitor  ...  n_moa  ativo_moa
0  id_000644bb2                            0  ...      1          1
1  id_000779bfc                            0  ...      0          0
2  id_000a6266a                            0  ...      3          1
3  id_0015fd391                            0  ...      0          0
4  id_001626bd3                            0  ...      1          1

[5 rows x 209 columns]

In [8]:
df_total = pd.merge(df, df_resultados[['id','n_moa', 'ativo_moa']], on='id')
df_total.head()

id tratamento  tempo dose  ...     c98     c99  n_moa  ativo_moa
0  id_000644bb2  com_droga     24   D1  ...  0.3801  0.4176      1          1
1  id_000779bfc  com_droga     72   D1  ...  0.6077  0.7371      0          0
2  id_000a6266a  com_droga     48   D1  ... -1.4080  0.6931      3          1
3  id_0015fd391  com_droga     48   D1  ... -0.3876 -0.8154      0          0
4  id_001626bd3  com_droga     72   D2  ... -0.3786  0.7125      1          1

[5 rows x 879 columns]

In [9]:
df_total['Eh controle'] = (df_total['tratamento'] == 'com_controle')*1
df_total['Tempo eh 24'] = (df_total['tempo'] == 24)*1
df_total['Tempo eh 48'] = (df_total['tempo'] == 48)*1
df_total['Tempo eh 72'] = (df_total['tempo'] == 72)*1

#Máquinas preditivas

## Problema 5: Prevendo se o composto ativa dois MOAs específicos

No Problema 3 criamos modelos que previam se um composto ativava um MOA específico. Aqui faremos algo semelhante, mas agora com dois MOAs. 
Como no problema 3, queremos uma alta precisão para positivos e negativos. 


Vejamos novamente a lista dos MOAs mais ativados fazendo a soma das colunas em toda a tabela df_resultados.

In [10]:
df_resultados.iloc[:,1:].sum(axis = 0).sort_values(ascending = False)

n_moa                                         16844
ativo_moa                                     14447
nfkb_inhibitor                                  832
proteasome_inhibitor                            726
cyclooxygenase_inhibitor                        435
                                              ...  
steroid                                           6
nicotinic_receptor_agonist                        6
elastase_inhibitor                                6
erbb2_inhibitor                                   1
atp-sensitive_potassium_channel_antagonist        1
Length: 208, dtype: int64

Assim, os MOAs mais ativados são nfkb_inhibitor e proteasome_inhibitor. Usaremos esses dois em nosso modelo.
Precisamos criar um novo data frame usando merge, para incluir as informações sobre expressões gênicas e uma coluna que nos informará se os dois MOAs foram ativados.

In [11]:
df_moa_ativado = pd.merge(df.iloc[:,0:200], df_resultados[['id','proteasome_inhibitor', 'nfkb_inhibitor']], on='id')
df_moa_ativado['ativou os dois'] = (df_moa_ativado['proteasome_inhibitor']+df_moa_ativado['nfkb_inhibitor'] ==2)*1
df_moa_ativado

id    tratamento  ...  nfkb_inhibitor ativou os dois
0      id_000644bb2     com_droga  ...               0              0
1      id_000779bfc     com_droga  ...               0              0
2      id_000a6266a     com_droga  ...               0              0
3      id_0015fd391     com_droga  ...               0              0
4      id_001626bd3     com_droga  ...               0              0
...             ...           ...  ...             ...            ...
23809  id_fffb1ceed     com_droga  ...               0              0
23810  id_fffb70c0c     com_droga  ...               0              0
23811  id_fffc1c3f4  com_controle  ...               0              0
23812  id_fffcb9e7c     com_droga  ...               0              0
23813  id_ffffdd77b     com_droga  ...               0              0

[23814 rows x 203 columns]

In [12]:
df_moa_ativado['Eh controle'] = (df_moa_ativado['tratamento'] == 'com_controle')*1
df_moa_ativado['Tempo eh 24'] = (df_moa_ativado['tempo'] == 24)*1
df_moa_ativado['Tempo eh 48'] = (df_moa_ativado['tempo'] == 48)*1
df_moa_ativado['Tempo eh 72'] = (df_moa_ativado['tempo'] == 72)*1

Criando as variáveis:

In [13]:
y = df_moa_ativado['ativou os dois']
x_aux = df_moa_ativado.drop(['id', 'tratamento','composto' ,'dose', 'tempo', 'proteasome_inhibitor', 'nfkb_inhibitor','ativou os dois'], axis = 1)
x = x_aux.drop(x_aux.columns[200:873])

In [14]:
x

g0      g1      g2  ...  Tempo eh 24  Tempo eh 48  Tempo eh 72
0      1.0620  0.5577 -0.2479  ...            1            0            0
1      0.0743  0.4087  0.2991  ...            0            0            1
2      0.6280  0.5817  1.5540  ...            0            1            0
3     -0.5138 -0.2491 -0.2656  ...            0            1            0
4     -0.3254 -0.4009  0.9700  ...            0            0            1
...       ...     ...     ...  ...          ...          ...          ...
23809  0.1394 -0.0636 -0.1112  ...            1            0            0
23810 -1.3260  0.3478 -0.3743  ...            1            0            0
23811  0.3942  0.3756  0.3109  ...            0            1            0
23812  0.6660  0.2324  0.4392  ...            1            0            0
23813 -0.8598  1.0240 -0.1361  ...            0            0            1

[23814 rows x 199 columns]

Separando os conjuntos de treino e conjunto de teste.

In [15]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3, stratify = y)

Estamos prontos para começar a testar os modelos preditivos.
Como antes, vamos criar também um dataframe com informações sumarizadas das performaces de cada modelo. Assim:

In [16]:
lista_modelo = []
lista_score = []
lista_precision0 = [] 
lista_precision1 = []
lista_recall0 = []
lista_recall1 = []

### Regressão Logistica

In [17]:
modelo = LogisticRegression()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.90202939118265 %


In [18]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6925    5]
 [   2  213]]


In [19]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6930
           1       0.98      0.99      0.98       215

    accuracy                           1.00      7145
   macro avg       0.99      0.99      0.99      7145
weighted avg       1.00      1.00      1.00      7145



### DecisionTreeClassifier 

In [20]:
modelo = DecisionTreeClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.52414275717285 %


In [21]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6917   13]
 [  21  194]]


In [22]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6930
           1       0.94      0.90      0.92       215

    accuracy                           1.00      7145
   macro avg       0.97      0.95      0.96      7145
weighted avg       1.00      1.00      1.00      7145



### RandomFlorestClassifier

In [23]:
modelo = RandomForestClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.88803358992303 %


In [24]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6922    8]
 [   0  215]]


In [25]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6930
           1       0.96      1.00      0.98       215

    accuracy                           1.00      7145
   macro avg       0.98      1.00      0.99      7145
weighted avg       1.00      1.00      1.00      7145



### LGBMClassifier

In [26]:
modelo = LGBMClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.8740377886634 %


In [27]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6924    6]
 [   3  212]]


In [28]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6930
           1       0.97      0.99      0.98       215

    accuracy                           1.00      7145
   macro avg       0.99      0.99      0.99      7145
weighted avg       1.00      1.00      1.00      7145



### XGBClassifier

In [29]:
modelo = XGBClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.88803358992303 %


In [30]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6923    7]
 [   1  214]]


In [31]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6930
           1       0.97      1.00      0.98       215

    accuracy                           1.00      7145
   macro avg       0.98      1.00      0.99      7145
weighted avg       1.00      1.00      1.00      7145



### GradientBoostingClassifier


In [32]:
modelo = GradientBoostingClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.84604618614415 %


In [33]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6924    6]
 [   5  210]]


In [34]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6930
           1       0.97      0.98      0.97       215

    accuracy                           1.00      7145
   macro avg       0.99      0.99      0.99      7145
weighted avg       1.00      1.00      1.00      7145



### KNeighborsClassifier

In [35]:
modelo = KNeighborsClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.73407977606718 %


In [36]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6911   19]
 [   0  215]]


In [37]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6930
           1       0.92      1.00      0.96       215

    accuracy                           1.00      7145
   macro avg       0.96      1.00      0.98      7145
weighted avg       1.00      1.00      1.00      7145



### Support Vector Machine

In [38]:
modelo = SVC()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  99.73407977606718 %


In [39]:
cm = confusion_matrix(y_teste, modelo.predict(x_teste))
lista_precision0.append(cm[0][0]/(cm[0][0]+cm[1][0]))
lista_precision1.append(cm[1][1]/(cm[1][1]+cm[0][1]))
lista_recall0.append(cm[0][0]/(cm[0][0]+cm[0][1]))
lista_recall1.append(cm[1][1]/(cm[1][1]+cm[1][0]))
print(cm)

[[6924    6]
 [  13  202]]


In [40]:
print(classification_report(y_teste, modelo.predict(x_teste)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6930
           1       0.97      0.94      0.96       215

    accuracy                           1.00      7145
   macro avg       0.98      0.97      0.98      7145
weighted avg       1.00      1.00      1.00      7145



### Resumo

In [41]:
Tabela_Performace_Modelos = pd.DataFrame()
Tabela_Performace_Modelos['Modelo'] = lista_modelo
Tabela_Performace_Modelos['Score'] = lista_score
Tabela_Performace_Modelos['precision-0'] = lista_precision0
Tabela_Performace_Modelos['precision-1'] = lista_precision1
Tabela_Performace_Modelos['recall-0'] = lista_recall0
Tabela_Performace_Modelos['recall-1'] = lista_recall1

Tabela_Comparação_Modelos_Problema5 = Tabela_Performace_Modelos
Tabela_Comparação_Modelos_Problema5

Modelo     Score  ...  recall-0  recall-1
0          LogisticRegression  0.999020  ...  0.999278  0.990698
1      DecisionTreeClassifier  0.995241  ...  0.998124  0.902326
2      RandomForestClassifier  0.998880  ...  0.998846  1.000000
3              LGBMClassifier  0.998740  ...  0.999134  0.986047
4               XGBClassifier  0.998880  ...  0.998990  0.995349
5  GradientBoostingClassifier  0.998460  ...  0.999134  0.976744
6        KNeighborsClassifier  0.997341  ...  0.997258  1.000000
7                         SVC  0.997341  ...  0.999134  0.939535

[8 rows x 6 columns]

Percebemos então que todos os modelos tiveram excelente desempenho, considerando todas as métricas. 

## Problema 6: prevendo a expressão gênica g0 a partir dos MOAs ativados

Estamos agora interessante em uma nova classe de problemas: os problemas de regressão. Nesse problema 6, gostaríamos de tentar prever o valor da expressão gênica g0 a partir dos MOAs que foram ativados. 
Começamos importando novas bibliotecas:

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import  MLPRegressor

Criando nosso data frame, usando o merge:

In [43]:
df_g0 = pd.merge(df.drop(df.columns[6:], axis = 1), df_resultados, on='id')

In [44]:
df_g0

id    tratamento  tempo  ... wnt_inhibitor n_moa  ativo_moa
0      id_000644bb2     com_droga     24  ...             0     1          1
1      id_000779bfc     com_droga     72  ...             0     0          0
2      id_000a6266a     com_droga     48  ...             0     3          1
3      id_0015fd391     com_droga     48  ...             0     0          0
4      id_001626bd3     com_droga     72  ...             0     1          1
...             ...           ...    ...  ...           ...   ...        ...
23809  id_fffb1ceed     com_droga     24  ...             0     1          1
23810  id_fffb70c0c     com_droga     24  ...             0     1          1
23811  id_fffc1c3f4  com_controle     48  ...             0     0          0
23812  id_fffcb9e7c     com_droga     24  ...             0     1          1
23813  id_ffffdd77b     com_droga     72  ...             0     0          0

[23814 rows x 214 columns]

Criando nossas variáveis:

In [45]:
y = df_g0['g0']
x = df_g0.drop(['id', 'tratamento', 'tempo', 'dose', 'composto', 'g0'], axis = 1)

In [46]:
x

5-alpha_reductase_inhibitor  11-beta-hsd1_inhibitor  ...  n_moa  ativo_moa
0                                0                       0  ...      1          1
1                                0                       0  ...      0          0
2                                0                       0  ...      3          1
3                                0                       0  ...      0          0
4                                0                       0  ...      1          1
...                            ...                     ...  ...    ...        ...
23809                            0                       0  ...      1          1
23810                            0                       0  ...      1          1
23811                            0                       0  ...      0          0
23812                            0                       0  ...      1          1
23813                            0                       0  ...      0          0

[23814 rows x 208 columns]

In [47]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3)

In [48]:
lista_modelo = []
lista_score = []

### Regressão Linear

In [49]:
modelo = LinearRegression()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  -1.5191127387715377e+22 %


### DecisionTreeRegressor

In [50]:
modelo = DecisionTreeRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  42.82408507876403 %


### RandomFlorestRegressor

In [51]:
modelo = RandomForestRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  42.91012147375143 %


### XGBR Regressor

In [52]:
modelo = XGBRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

[19:25:45] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
Score =  42.119040708065384 %


### LGBM Regressor

In [53]:
modelo = LGBMRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  41.5503912494968 %


### Gradiant Boosting Regressor

In [54]:
modelo = GradientBoostingRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  42.19580867600785 %


### KNeighbors Regressor

In [55]:
modelo = KNeighborsRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  34.736173148670304 %


### MLP Regressor

In [56]:
modelo = MLPRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  42.804499741678114 %


### Resumo

In [57]:
Tabela_Performace_Modelos = pd.DataFrame()
Tabela_Performace_Modelos['Modelo'] = lista_modelo
Tabela_Performace_Modelos['Score'] = lista_score

Tabela_Comparação_Modelos_Problema6 = Tabela_Performace_Modelos
Tabela_Comparação_Modelos_Problema6

Modelo         Score
0           LinearRegression -1.519113e+20
1      DecisionTreeRegressor  4.282409e-01
2      RandomForestRegressor  4.291012e-01
3               XGBRegressor  4.211904e-01
4              LGBMRegressor  4.155039e-01
5  GradientBoostingRegressor  4.219581e-01
6        KNeighborsRegressor  3.473617e-01
7               MLPRegressor  4.280450e-01

Concluímos então que para esse problema, os modelos tiveram um desempenho pífio. 
Isso talvez se explique pelo fato de que usamos variáveis categóricas (de fato, binárias) para tentar prever uma variável contínua. 

## Problema 7: prevendo a viabilidade celular a partir das expressões gênicas.

Queremos agora saber se é possível recupear as viabilidades celulares, sabendo as expressões gênicas. Como as variáveis c0-c99 são muito correlacionadas, basta verificar para uma delas, digamos, c0.

Criando as variáveis:

In [58]:
y = df['c0']
x_aux = df.drop(['id', 'tratamento', 'tempo', 'dose', 'composto'],  axis = 1)
x = x_aux.iloc[:,0:200]

In [59]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3)

In [60]:
lista_modelo = []
lista_score = []

### Regressão Linear

In [61]:
modelo = LinearRegression()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  80.75826966907434 %


### DecisionTreeRegressor

In [62]:
modelo = DecisionTreeRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')
  


Score =  63.677903638685194 %


### RandomFlorestRegressor

In [63]:
modelo = RandomForestRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  82.41144193682692 %


### XGBR Regressor

In [64]:
modelo = XGBRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

[19:34:41] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
Score =  82.84268528095438 %


### LGBM Regressor

In [65]:
modelo = LGBMRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  83.01265384799555 %


### Gradiant Boosting Regressor

In [66]:
modelo = GradientBoostingRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  82.82455517762588 %


### KNeighbors Regressor

In [67]:
modelo = KNeighborsRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  80.14757112986595 %


### MLP Regressor

In [68]:
modelo = MLPRegressor()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  75.14327537803901 %


### Resumo

In [69]:
Tabela_Performace_Modelos = pd.DataFrame()
Tabela_Performace_Modelos['Modelo'] = lista_modelo
Tabela_Performace_Modelos['Score'] = lista_score

Tabela_Comparação_Modelos_Problema7 = Tabela_Performace_Modelos
Tabela_Comparação_Modelos_Problema7

Modelo     Score
0           LinearRegression  0.807583
1      DecisionTreeRegressor  0.636779
2      RandomForestRegressor  0.824114
3               XGBRegressor  0.828427
4              LGBMRegressor  0.830127
5  GradientBoostingRegressor  0.828246
6        KNeighborsRegressor  0.801476
7               MLPRegressor  0.751433

Vemos então que, com excessão dos modelos de árvore de decisão e MLP, todos os modelos apresentaram desempenho satisfatório. 

## Problema 8: prevendo o composto a partir das expressões gênicas

Deixamos agora os problemas de regressão e voltamos aos problemas de classificação. Mas desta vez, estamos interessando em problemas de classificação não-binária. Isto é, temos mais duas classes.
Nesse e no próximo problema, queremos prever o composto, primeiro a partir das expressões gênicas, e depois a partir dos MOAs ativados. 

Vamos nos limitar, porém, apenas aos nove compostos mais frequentes, para termos dados mais consistentes. Vamos descartar também o composto do grupo de controle.

In [70]:
#pegando a lista dos compostos mais frequentes
top_composto = df['composto'].value_counts()[1:9].index
top_composto

Index(['87d714366', '9f80f3f77', '8b87a7a83', '5628cb3ee', 'd08af5d4b',
       '292ab2c28', 'd50f18348', 'd1b47f29d'],
      dtype='object')

Filtrando nosso dataframe pelos compostos mais frequentes:

In [71]:
df_top = df_total.query('composto in @top_composto')
df_top

id tratamento  tempo  ... Tempo eh 24 Tempo eh 48  Tempo eh 72
7      id_0020d0484  com_droga     48  ...           0           1            0
16     id_002fb9c19  com_droga     48  ...           0           1            0
39     id_0079d45d3  com_droga     24  ...           1           0            0
44     id_00872d938  com_droga     48  ...           0           1            0
48     id_008b48693  com_droga     24  ...           1           0            0
...             ...        ...    ...  ...         ...         ...          ...
23782  id_ffb12855e  com_droga     72  ...           0           0            1
23791  id_ffd1fd119  com_droga     72  ...           0           0            1
23802  id_fff3976bd  com_droga     24  ...           1           0            0
23805  id_fff6df1c5  com_droga     48  ...           0           1            0
23812  id_fffcb9e7c  com_droga     24  ...           1           0            0

[2123 rows x 883 columns]

Criando as variáveis:

In [72]:
y = df_top['composto']
x = df_top.drop(['composto', 'id', 'tempo', 'dose', 'tratamento'], axis = 1).iloc[:,0:771]

In [73]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3)

In [74]:
lista_modelo = []
lista_score = []

### Regressão Logísitica

In [75]:
modelo = LogisticRegression()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  98.74411302982732 %


### DecisionTreeClassifier

In [76]:
modelo = DecisionTreeClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  87.91208791208791 %


###RandomFlorestClassifier

In [77]:
modelo = RandomForestClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  97.17425431711146 %


### XBG Classifier

In [78]:
modelo = XGBClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  97.48822605965462 %


### LGBM Classifier

In [79]:
modelo = LGBMClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  97.01726844583987 %


### GradientBoostClassifier


In [80]:
modelo = GradientBoostingClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  97.48822605965462 %


### KNeighbors Classifier

In [81]:
modelo = KNeighborsClassifier(n_neighbors=8)
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  91.67974882260597 %


### MLP Classifier

In [82]:
modelo = MLPClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  98.43014128728414 %


### Resumo

In [83]:
Tabela_Performace_Modelos = pd.DataFrame()
Tabela_Performace_Modelos['Modelo'] = lista_modelo
Tabela_Performace_Modelos['Score'] = lista_score

Tabela_Comparação_Modelos_Problema8 = Tabela_Performace_Modelos
Tabela_Comparação_Modelos_Problema8  

Modelo     Score
0          LogisticRegression  0.987441
1      DecisionTreeClassifier  0.879121
2      RandomForestClassifier  0.971743
3               XGBClassifier  0.974882
4              LGBMClassifier  0.970173
5  GradientBoostingClassifier  0.974882
6        KNeighborsClassifier  0.916797
7               MLPClassifier  0.984301

Vemos então que todos os modelos tiveram desempenho excelente nesse problema. Importante notar que novamente, o modelo de árvore de decisão foi o menos preciso. 

## Problema 9: prevendo o composto a partir dos MOAs ativados

Para finalizar, em nosso último problema vamos construir modelos para prever o composto sabendo os MOAs que ele ativou.

In [84]:
#pegando a lista dos compostos mais frequentes
top_composto = df['composto'].value_counts()[1:9].index
top_composto

Index(['87d714366', '9f80f3f77', '8b87a7a83', '5628cb3ee', 'd08af5d4b',
       '292ab2c28', 'd50f18348', 'd1b47f29d'],
      dtype='object')

In [85]:
df_moas = pd.merge(df.drop(df.columns[5:], axis = 1), df_resultados, on='id')
df_moas

id    tratamento  tempo  ... wnt_inhibitor n_moa  ativo_moa
0      id_000644bb2     com_droga     24  ...             0     1          1
1      id_000779bfc     com_droga     72  ...             0     0          0
2      id_000a6266a     com_droga     48  ...             0     3          1
3      id_0015fd391     com_droga     48  ...             0     0          0
4      id_001626bd3     com_droga     72  ...             0     1          1
...             ...           ...    ...  ...           ...   ...        ...
23809  id_fffb1ceed     com_droga     24  ...             0     1          1
23810  id_fffb70c0c     com_droga     24  ...             0     1          1
23811  id_fffc1c3f4  com_controle     48  ...             0     0          0
23812  id_fffcb9e7c     com_droga     24  ...             0     1          1
23813  id_ffffdd77b     com_droga     72  ...             0     0          0

[23814 rows x 213 columns]

In [86]:
df_top = df_moas.query('composto in @top_composto')
df_top

id tratamento  tempo  ... wnt_inhibitor n_moa  ativo_moa
7      id_0020d0484  com_droga     48  ...             0     1          1
16     id_002fb9c19  com_droga     48  ...             0     2          1
39     id_0079d45d3  com_droga     24  ...             0     0          0
44     id_00872d938  com_droga     48  ...             0     0          0
48     id_008b48693  com_droga     24  ...             0     1          1
...             ...        ...    ...  ...           ...   ...        ...
23782  id_ffb12855e  com_droga     72  ...             0     1          1
23791  id_ffd1fd119  com_droga     72  ...             0     2          1
23802  id_fff3976bd  com_droga     24  ...             0     2          1
23805  id_fff6df1c5  com_droga     48  ...             0     1          1
23812  id_fffcb9e7c  com_droga     24  ...             0     1          1

[2123 rows x 213 columns]

In [87]:
y = df_top['composto']
x = df_top.drop(['composto', 'id', 'tempo', 'dose', 'tratamento'], axis = 1)

In [88]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3)

In [89]:
lista_modelo = []
lista_score = []

### Regressão Logísitica

In [90]:
modelo = LogisticRegression()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  100.0 %


### DecisionTreeClassifier

In [92]:
modelo = DecisionTreeClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  100.0 %


###RandomFlorestClassifier

In [93]:
modelo = RandomForestClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  100.0 %


In [94]:
lista = (modelo.predict(x_teste) == y_teste)*1
lista.sum(), y_teste.shape

(637, (637,))

### XBG Classifier

In [95]:
modelo = XGBClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  100.0 %


### LGBM Classifier

In [96]:
modelo = LGBMClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  100.0 %


### GradientBoostClassfier


In [97]:
modelo = GradientBoostingClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  100.0 %


### KNeighbors Classifier

In [98]:
modelo = KNeighborsClassifier(n_neighbors=8)
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  100.0 %


### MLP Classifier

In [99]:
modelo = MLPClassifier()
lista_modelo.append(str(modelo).split('(')[0])
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
lista_score.append(resultado)
print('Score = ', resultado*100, '%')

Score =  100.0 %


### Resumo

In [100]:
Tabela_Performace_Modelos = pd.DataFrame()
Tabela_Performace_Modelos['Modelo'] = lista_modelo
Tabela_Performace_Modelos['Score'] = lista_score

Tabela_Comparação_Modelos_Problema9 = Tabela_Performace_Modelos
Tabela_Comparação_Modelos_Problema9  

Modelo  Score
0          LogisticRegression    1.0
1      DecisionTreeClassifier    1.0
2      RandomForestClassifier    1.0
3               XGBClassifier    1.0
4              LGBMClassifier    1.0
5  GradientBoostingClassifier    1.0
6        KNeighborsClassifier    1.0
7               MLPClassifier    1.0

Vemos então que nesse último problema os modelos tiveram uma performace perfeita, com 100% de acerto. Faz sentido, pois é de se esperar que compostos distintos ativem conjuntos distintos de MOAs.

